name: Bug report
description: Report a reproducible bug in wabi_tree
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug! Please include as much detail as you can.

  - type: input
    id: version
    attributes:
      label: Crate version
      description: The wabi_tree version (e.g. 0.1.0)
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust
    attributes:
      label: Rust version
      description: Output of `rustc --version`
      placeholder: "rustc 1.xx.x (....)"
    validations:
      required: true

  - type: dropdown
    id: target
    attributes:
      label: Target / environment
      options:
        - x86_64-unknown-linux-gnu
        - x86_64-apple-darwin
        - aarch64-apple-darwin
        - x86_64-pc-windows-msvc
        - Other (please describe below)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps / minimal example
      description: Ideally a minimal snippet or a link to a small repo.
      render: rust
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / backtraces
      description: If relevant, include panic output, backtrace, or error messages.
      render: text
    validations:
      required: false