name: Feature request
description: Propose a new feature or improvement for wabi_tree
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement! Data structure crates benefit a lot from clear use-cases and constraints.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve? Why is the current behavior insufficient?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or workarounds you've tried?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Benchmarks, API sketches, example usage, links, etc.
    validations:
      required: false